#ifndef __CONVERTDATA_H
#define __CONVERTDATA_H
enum Digit {MINUS_ONE=-1,ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,TEN};
enum ClusterMode {MAFIA_FORMAT=-6,LDR_FORMAT,WEKA_FORMAT,IBM_DATA_FORMAT,ASC_TO_BIN,HORZ_TO_VERT,OKCLUSTER,KCLUSTER,COMPARE,HCLUSTER,VHEIRARCHY,ECLUSTER,JCLUSTER,VCLUSTER,IMP_VCLUSTER,OPT_VCLUSTER};
const static int NUM_ARGS=TWO;
const static int MAX_LINE_SIZE = 16384;
const static int MAX_COORD_SIZE = TEN;
static int iPointCnt = ZERO;
static int NO_OF_DIMENSIONS = 50,START_DIMENSION = ZERO,NO_OF_POINTS = 1000,NORM = 10,iMode=-3,iNoOfDatasets=1;
static char DELIMITER = ' ';
static int iNoOfPts;
static float MAX = 1000.0,MIN = 0.0;
const double OFFSET = 0.00000000000005;
#endif
